---
name: SBT Test

on:
#  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: sbtscala/scala-sbt:1.8_1.9.3_3.3.0
    steps:
      - name: SBT action test
        id: sbt
        uses: lokkju/github-action-sbt@master
        with:
          commands: test
          sbt_project_directory: ./test